### ISSUE TITLE
Autoclose Powerpoint after export

### ISSUE THREAD

**Issue by ghost** [DmitrySavritsky/Slide-to-image-4K#1]
Hello an thank you for this awesome tool!
I have a suggestion: is it possibly to automatically close PowerPoint window after I exported slides to images?

**Comment by DmitrySavritsky** [comment]
Hmm, it is looks strange, because PowerPoint should close immediately after export. Could you send me your PowerPoint file for the test?

**Comment by ghost** [comment]
Seems that now everything is ok, the app works as it should. Thanks anyway.
